name: coinTalk chatRoom server CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  S3_BUCKET_NAME: cointalk-deploy
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  TOKEN_HEADER_PREFIX: ${{ secrets.TOKEN_HEADER_PREFIX }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build -P JWT_SECRET_KEY="${JWT_SECRET_KEY}" -P TOKEN_HEADER_PREFIX="${TOKEN_HEADER_PREFIX}"
